12.0 afc 1330
vertelab/odoo-hr pull request #34
Opened 2020-12-14 16:32 UTC by SebastianGieser-Vertel

2020-12-14 19:10 UTC, FredrikArvas commented
I believe the system-id should be AFDAFA in test.
![image](https://user-images.githubusercontent.com/9428370/102124278-5a63f600-3e48-11eb-95a7-904861c21314.png)

2020-12-15 08:44 UTC, arturchilangwa-vertel requested changes
Only one small change needed!

2020-12-15 08:44 UTC, arturchilangwa-vertel commented on hr_employee_ciam_client/models/client_config.py
> +
Unnecessary space

2020-12-15 08:59 UTC, arturchilangwa-vertel approved these changes

2020-12-15 09:02 UTC, arturchilangwa-vertel requested changes
https://github.com/vertelab/odoo-hr/pull/34#issuecomment-744648576

2020-12-15 09:02 UTC, arturchilangwa-vertel commented on hr_employee_ciam_client/models/client_config.py
> +            'AF-EndUserId': "*sys*",
Check Fredriks comment on this
https://github.com/vertelab/odoo-hr/pull/34#issuecomment-744648576

2020-12-15 09:10 UTC, arturchilangwa-vertel approved these changes

2020-12-15 09:22 UTC, merged